[platformio]
src_dir = src/

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Match Windows flash.bat: PartitionScheme=huge_app
board_build.partitions = huge_app.csv

monitor_speed = 115200
upload_speed = 921600
